AWSTemplateFormatVersion: "2010-09-09"
Description: Stack Alarms
Transform: AWS::Serverless-2016-10-31

Parameters:
  AlertSNSArn:
    Description: SNS Queue to send general alarm alerts to
    Type: String
  PriorityAlertSNSArn:
    Description: SNS Queue to send priority alarm alerts to
    Type: String
  ApplicationPrefix:
    Type: String
    Description: Application prefix, no ending dash
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
  ApplicationFriendlyName:
    Type: String
    Description: Application friendly name that will be used in resource descriptions


Resources:
  AppDLQMessagesAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Condition: IsProd
    Properties:
      AlarmName: !Sub ${ApplicationPrefix}-sqs-dlq
      AlarmDescription: "Items are present in the application DLQ, meaning some messages failed to process."
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Statistic: "Maximum"
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: "GreaterThanThreshold"
      Threshold: 0
      Dimensions:
        - Name: QueueName
          Value: !Sub ${ApplicationPrefix}-sqs-dlq
      AlarmActions:
        - !Ref PriorityAlertSNSArn
