Parameters:
  GWBaseDomainName:
    Description: Base domain name
    Type: String
  RunEnvironment:
    Type: String
    AllowedValues: [ 'dev', 'prod' ]
  RecordName:
    Type: String
  CloudfrontDomain:
    Type: String

Conditions:
  IsDev: !Equals [!Ref RunEnvironment, 'dev']

Resources:

  CDRoute53RecordSetDev:
    Condition: IsDev
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref GWHostedZoneId
      Name: !Sub "${RecordName}.${GWBaseDomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !Ref CloudfrontDomain
