Parameters:
  GWCertArn:
    Description: Certificate ARN
    Type: String
  GWBaseDomainName:
    Description: Base domain name
    Type: String
  GWApiId:
    Description: API ID
    Type: String
  GWHostedZoneId:
    Description: Hosted Zone ID
    Type: String
  RunEnvironment:
    Type: String
    AllowedValues: [ 'dev', 'prod' ]
  RecordName:
    Type: String
  CloudfrontDomain:
    Type: String

Conditions:
  IsDev: !Equals [!Ref RunEnvironment, 'dev']

Resources:
  CustomDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      RegionalCertificateArn: !Ref GWCertArn
      EndpointConfiguration:
        Types:
          - REGIONAL
      DomainName: !Sub "${RecordName}.${GWBaseDomainName}"
      SecurityPolicy: TLS_1_2

  CDApiMapping:
    Type: 'AWS::ApiGatewayV2::ApiMapping'
    Properties:
      DomainName: !Ref CustomDomainName
      ApiId: !Ref GWApiId
      Stage: default

  CDRoute53RecordSetDev:
    Condition: IsDev
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref GWHostedZoneId
      Name: !Sub "${RecordName}.${GWBaseDomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !Ref CloudfrontDomain
