AWSTemplateFormatVersion: 2010-09-09
Description: ACM Core Management Platform
Transform: AWS::Serverless-2016-10-31

Parameters:
  RunEnvironment:
    Type: String
    AllowedValues: ["dev", "prod"]
  ApplicationPrefix:
    Type: String
    Description: Application prefix, no ending dash
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
  ApplicationFriendlyName:
    Type: String
    Description: Application friendly name that will be used in resource descriptions
  VpcRequired:
    Description: Set to true if the default lambda should be attached to a VPC and a NoVPC version of the lambda should be created. Lambdas to be attached to VPCs to access Postgres.
    Default: false
    Type: String
    AllowedValues: [true, false]
  SqsLambdaTimeout:
    Description: How long the SQS lambda is permitted to run (in seconds)
    Default: 180
    Type: Number
  S3BucketPrefix:
    Description: S3 bucket prefix which will ensure global uniqueness
    Type: String
  CloudfrontOriginSecret:
    NoEcho: true
    Description: Value for X-Origin-Verify passed to Lambda URL from cloudfront
    Type: String

Conditions:
  IsDev: !Equals [!Ref RunEnvironment, "dev"]
  ShouldAttachVpc: !Equals [true, !Ref VpcRequired]

Mappings:
  General:
    dev:
      SesDomain: "aws.qa.acmuiuc.org"
    prod:
      SesDomain: "acm.illinois.edu"
  ApiGwConfig:
    dev:
      HostedZoneId: Z04502822NVIA85WM2SML
      UiDomainName: "core.aws.qa.acmuiuc.org"
      EnvDomainName: "aws.qa.acmuiuc.org"
      EnvCertificateArn: arn:aws:acm:us-east-1:427040638965:certificate/63ccdf0b-d2b5-44f0-b589-eceffb935c23
    prod:
      HostedZoneId: Z05246633460N5MEB9DBF
      UiDomainName: "core.acm.illinois.edu"
      EnvDomainName: "acm.illinois.edu"
      EnvCertificateArn: arn:aws:acm:us-east-1:298118738376:certificate/aeb93d9e-b0b7-4272-9c12-24ca5058c77e
  EnvironmentToCidr:
    dev:
      SecurityGroupIds:
        - sg-00443e61d39721a0d
        - sg-0e99aa1c1e4e9e5b6
      SubnetIds:
        - subnet-0cd2b887e61f6edd8
        - subnet-065857a2bdf3a51aa
        - subnet-09e12f156435e4cc9
    prod:
      SecurityGroupIds:
        - sg-066e3ae1d05e70fcd
      SubnetIds:
        - subnet-0cf33aff80b81eb1b
        - subnet-0cbe89f6ab2665610

Resources:

  LinkryRecordSetv4:
    Condition: IsDev
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !FindInMap [ApiGwConfig, !Ref RunEnvironment, HostedZoneId]
      Name: !Join
        - "."
        - - "go"
          - !FindInMap
            - ApiGwConfig
            - !Ref RunEnvironment
            - EnvDomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt [AppLinkryCloudfrontDistribution, DomainName]
        EvaluateTargetHealth: false

  LinkryRecordSetv6:
    Condition: IsDev
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !FindInMap [ApiGwConfig, !Ref RunEnvironment, HostedZoneId]
      Name: !Join
        - "."
        - - "go"
          - !FindInMap
            - ApiGwConfig
            - !Ref RunEnvironment
            - EnvDomainName
      Type: AAAA
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt [AppLinkryCloudfrontDistribution, DomainName]
        EvaluateTargetHealth: false


  AppLinkryCloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: 'http2and3'
        Enabled: true
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: dummyOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt LinkryRecordsCloudfrontFunction.FunctionARN
        Origins:
          - Id: dummyOrigin
            DomainName: example.com
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        Aliases:
          - !Join
            - ""
            - - "go."
              - !FindInMap
                - ApiGwConfig
                - !Ref RunEnvironment
                - EnvDomainName
        ViewerCertificate:
          AcmCertificateArn: !FindInMap
            - ApiGwConfig
            - !Ref RunEnvironment
            - EnvCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        PriceClass: PriceClass_100

Outputs:
  DomainName:
    Description: Domain name that the UI is hosted at
    Value: !FindInMap
      - ApiGwConfig
      - !Ref RunEnvironment
      - UiDomainName

  CloudfrontCnameTarget:
    Description: CNAME record target to create for the domain name above (create the CNAME manually)
    Value:
      Fn::GetAtt:
        - AppFrontendCloudfrontDistribution
        - DomainName

  CloudfrontSecondaryCnameTarget:
    Description: CNAME record target to create for the secondary domain names (create the CNAME manually)
    Value:
      Fn::GetAtt:
        - AppIcalCloudfrontDistribution
        - DomainName

  CloudfrontDistributionId:
    Description: Cloudfront Distribution ID
    Value: !GetAtt AppFrontendCloudfrontDistribution.Id

  CloudfrontIcalDistributionId:
    Description: Cloudfront Distribution ID
    Value: !GetAtt AppIcalCloudfrontDistribution.Id

  SalesEmailQueueArn:
    Description: Sales Email Queue Arn
    Value: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:infra-core-api-sqs-sales"
