export const HTTP_ERROR_MESSAGES: Record<number, string> = {
  // 4xx Client Errors
  400: "The request was invalid. Please check your input and try again.",
  401: "You need to log in to access this resource.",
  402: "Payment is required to access this resource.",
  403: "You don't have permission to access this resource.",
  404: "The page or resource you're looking for doesn't exist.",
  405: "This action is not allowed.",
  406: "The server can't return data in the format you requested.",
  407: "Proxy authentication is required.",
  408: "The request took too long. Please try again.",
  409: "There was a conflict with the current state of the resource. Please refresh and try again.",
  410: "This resource has been permanently removed.",
  411: "The request is missing a required content length.",
  412: "A precondition for this request was not met.",
  413: "The data you're sending is too large. Please reduce the size and try again.",
  414: "The URL is too long for the server to process.",
  415: "The file or data format is not supported.",
  416: "The requested data range is not available.",
  417: "The server could not meet the requirements of the request.",
  418: "I'm a teapot. ☕",
  421: "The request was directed to the wrong server.",
  422: "The request was well-formed but contains invalid data. Please check your input.",
  423: "This resource is currently locked.",
  424: "This request failed because a previous related request failed.",
  425: "The server is unwilling to process this request because it may be replayed.",
  426: "Please upgrade your connection protocol to proceed.",
  428: "This request requires specific preconditions to be included.",
  429: "You've made too many requests. Please wait a moment and try again.",
  431: "The request headers are too large.",
  451: "This content is unavailable for legal reasons.",

  // 5xx Server Errors
  500: "Something went wrong on our end. Please try again later.",
  501: "This feature is not yet supported.",
  502: "We're having trouble connecting to the server. Please try again shortly.",
  503: "The service is temporarily unavailable. Please try again later.",
  504: "The server took too long to respond. Please try again.",
  505: "The HTTP version used in your request is not supported.",
  506: "A server configuration error occurred.",
  507: "The server has run out of storage space.",
  508: "A loop was detected while processing your request.",
  510: "Additional extensions are required to fulfill this request.",
  511: "You need to authenticate to gain network access.",
} as const;
