name: test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: mysql-shutdown
      run: sudo service mysql stop
    - name: mysql-setup
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'core-test'
        mysql user: 'devuser'
        mysql password: 'devpass'
    - name: mysql-permission
      run: sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'devuser'@'%'"";
    - name: build
      run: make all
    - name: migration
      run: make migration
    - name: unit-test
      run: make test
