name: AWS STS Identity Check

on:
  workflow_dispatch:

jobs:
  check-aws-identity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::427040638965:role/GitHubActionsRole
          role-session-name: Core_QA_Deployment
          aws-region: us-east-1

      - name: Get AWS Caller Identity
        run: aws sts get-caller-identity
